import {
  EngineFilterImage,
  BrakePadImage,
  HondaGearBoxImage1,
  HondaGearBoxImage2,
  HondaGearBoxImage3,
  HondaGearBoxImage4,
} from '@app/assets/svg';

export default productCardData = [
  {
    id: 1,
    productCardCategory: 'HondaGearBoxImage1',
    productCardImage: <HondaGearBoxImage1 />,
    productCardTitle: 'Honda Gear Box',
    productCardSubTitle: 'Lorem ipsum',
    productCardPrice: 1999,
  },
  {
    id: 2,
    productCardCategory: 'HondaGearBoxImage2',
    productCardImage: <HondaGearBoxImage2 />,
    productCardTitle: 'Gear box 2',
    productCardSubTitle: 'Lorem ipsum',
    productCardPrice: 1999,
  },
  {
    id: 3,
    productCardCategory: 'HondaGearBoxImage3',
    productCardImage: <HondaGearBoxImage3 />,
    productCardTitle: 'gear box 3',
    productCardSubTitle: 'Lorem ipsum',
    productCardPrice: 1999,
  },
  {
    id: 4,
    productCardCategory: 'HondaGearBoxImage4',
    productCardImage: <HondaGearBoxImage4 />,
    productCardTitle: 'gear box 4',
    productCardSubTitle: 'Lorem ipsum',
    productCardPrice: 1999,
  },
  {
    id: 5,
    productCardCategory: 'EngineFilterImage',
    productCardImage: <EngineFilterImage />,
    productCardTitle: 'Engine Filter',
    productCardSubTitle: 'Lorem ipsum',
    productCardPrice: 1999,
  },
  {
    id: 6,
    productCardCategory: 'BrakePadImage',
    productCardImage: <BrakePadImage />,
    productCardTitle: 'Brake Pad',
    productCardSubTitle: 'Lorem ipsum',
    productCardPrice: 1999,
  },
  {
    id: 7,
    productCardCategory: 'EngineFilterImage',
    productCardImage: <EngineFilterImage />,
    productCardTitle: 'Engine Filter',
    productCardSubTitle: 'Lorem ipsum',
    productCardPrice: 1999,
  },
  {
    id: 8,
    productCardCategory: 'BrakePadImage',
    productCardImage: <BrakePadImage />,
    productCardTitle: 'Brake Pad',
    productCardSubTitle: 'Lorem ipsum',
    productCardPrice: 1999,
  },
];
